### ISSUE TITLE
Make userstyle for Sabaki v0.14.0

### ISSUE THREAD

**Issue by yishn** [fohristiwhirl/sabaki_subdued_theme#1]
As of Sabaki v0.14.0 there's the possibility of making a userstyle, an easy way to change Sabaki's appearance without having to replace any important files. Look at [this tutorial](https://github.com/yishn/Sabaki/wiki/Userstyle-Tutorial) and [this theme](https://github.com/yishn/sabaki_photorealistic_theme) for guidance. Afterwards you can add your theme to [this list](https://github.com/yishn/Sabaki/wiki/Userstyles) if you want to. :smiley:

**Comment by rooklift** [comment]
Thanks, will try my best
